name: Create GitHub Release

on:
    push:
        tags:
            - "v*" # Run when tag matches v*, e.g. v1.0.0

permissions:
    contents: write # For creating releases

jobs:
    build_release:
        name: Build and Create GitHub Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Required for git-cliff to work properly

            - name: Install git-cliff
              uses: orhun/git-cliff-action@v2
              with:
                  config: cliff.toml
                  args: --verbose

            - name: Extract version from tag
              id: tag_parser
              run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

            - name: Generate release notes
              run: |
                  # Generate release notes for this specific tag
                  git cliff --tag v${{ steps.tag_parser.outputs.VERSION }} --output release_notes.md --strip-header

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  name: v${{ steps.tag_parser.outputs.VERSION }}
                  body_path: release_notes.md
                  files: |
                      LICENSE
                      CHANGELOG.md
