name: Prepare and Publish Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Release version (without v prefix)"
                required: false
                type: string
            level:
                description: "Release level (if version not specified)"
                required: false
                default: "patch"
                type: choice
                options:
                    - patch
                    - minor
                    - major
                    - release
                    - rc
                    - beta
                    - alpha
            dry-run:
                description: "Dry run (no actual changes)"
                required: false
                default: false
                type: boolean

permissions:
    contents: write # For git push, creating tags

jobs:
    release:
        name: Prepare and Publish Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ github.token }}

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Cache dependencies
              uses: Swatinem/rust-cache@v2

            - name: Set Git identity
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions@github.com"

            - name: Install cargo-release
              run: cargo install cargo-release

            - name: Install git-cliff
              uses: orhun/git-cliff-action@v2
              with:
                  config: cliff.toml
                  args: --verbose

            - name: Build version arguments
              id: version_args
              run: |
                  if [ "${{ inputs.version }}" != "" ]; then
                    # Manual version
                    echo "VERSION_ARG=--version ${{ inputs.version }}" >> $GITHUB_OUTPUT
                    echo "VERSION=${{ inputs.version }}" >> $GITHUB_OUTPUT
                  else
                    # Use level
                    echo "VERSION_ARG=${{ inputs.level }}" >> $GITHUB_OUTPUT

                    # Extract the current version from Cargo.toml and calculate the next version
                    CURRENT_VERSION=$(grep -m 1 'version = "' Cargo.toml | sed 's/.*version = "\(.*\)".*/\1/')

                    # Simple version calculation
                    if [ "${{ inputs.level }}" = "patch" ]; then
                      IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
                      NEXT_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$((VERSION_PARTS[2] + 1))"
                    elif [ "${{ inputs.level }}" = "minor" ]; then
                      IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
                      NEXT_VERSION="${VERSION_PARTS[0]}.$((VERSION_PARTS[1] + 1)).0"
                    elif [ "${{ inputs.level }}" = "major" ]; then
                      IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
                      NEXT_VERSION="$((VERSION_PARTS[0] + 1)).0.0"
                    else
                      # For other levels, we'll just record the current version
                      NEXT_VERSION="$CURRENT_VERSION"
                    fi

                    echo "VERSION=$NEXT_VERSION" >> $GITHUB_OUTPUT
                  fi

                  if [ "${{ inputs.dry-run }}" = "true" ]; then
                    echo "DRY_RUN=true" >> $GITHUB_OUTPUT
                  else
                    echo "DRY_RUN=false" >> $GITHUB_OUTPUT
                  fi

            - name: Show workspace configuration
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
                  WORKSPACE_ROOT: ${{ github.workspace }}
              run: cargo release config

            - name: Run release process
              if: ${{ steps.version_args.outputs.DRY_RUN == 'false' }}
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
                  WORKSPACE_ROOT: ${{ github.workspace }}
                  # Use the built-in token for Git operations
                  GIT_CREDENTIALS: https://x-access-token:${{ github.token }}@github.com
              run: |
                  echo "Running cargo release with args: ${{ steps.version_args.outputs.VERSION_ARG }}"

                  # Execute each step explicitly and in order
                  cargo release version ${{ steps.version_args.outputs.VERSION_ARG }} --workspace --execute --no-confirm
                  cargo release replace --workspace --execute
                  cargo release hook --workspace --execute
                  cargo release commit --workspace --execute
                  cargo release publish --workspace --execute
                  cargo release tag --workspace --execute
                  cargo release push --workspace --execute

            - name: Run dry-run release process
              if: ${{ steps.version_args.outputs.DRY_RUN == 'true' }}
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
                  WORKSPACE_ROOT: ${{ github.workspace }}
              run: |
                  echo "Running cargo release dry run with args: ${{ steps.version_args.outputs.VERSION_ARG }}"

                  # Show what would happen in a dry run
                  cargo release version ${{ steps.version_args.outputs.VERSION_ARG }} --workspace --no-confirm
                  cargo release replace --workspace
                  cargo release hook --workspace
                  cargo release commit --workspace
                  cargo release publish --workspace
                  cargo release tag --workspace
                  cargo release push --workspace

            - name: Create summary
              run: |
                  echo "# Release Process Completed! 🚀" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  if [ "${{ steps.version_args.outputs.DRY_RUN }}" == "true" ]; then
                    echo "**DRY RUN**: No actual changes were made" >> $GITHUB_STEP_SUMMARY
                  else
                    echo "Version: ${{ steps.version_args.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
                    echo "" >> $GITHUB_STEP_SUMMARY
                    echo "The following actions were completed:" >> $GITHUB_STEP_SUMMARY
                    echo "- Version bumped to ${{ steps.version_args.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
                    echo "- CHANGELOG.md updated" >> $GITHUB_STEP_SUMMARY
                    echo "- Changes committed" >> $GITHUB_STEP_SUMMARY
                    echo "- Crates published to crates.io" >> $GITHUB_STEP_SUMMARY
                    echo "- Git tag created" >> $GITHUB_STEP_SUMMARY
                    echo "- Changes pushed to GitHub" >> $GITHUB_STEP_SUMMARY
                  fi
