name: Prepare and Publish Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Release version (without v prefix)"
                required: false
                type: string
            level:
                description: "Release level (if version not specified)"
                required: false
                default: "patch"
                type: choice
                options:
                    - patch
                    - minor
                    - major
                    - release
                    - rc
                    - beta
                    - alpha
            dry-run:
                description: "Dry run (no actual changes)"
                required: false
                default: false
                type: boolean

permissions:
    contents: write # For git push, creating tags

jobs:
    release:
        name: Prepare and Publish Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ github.token }}

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Cache dependencies
              uses: Swatinem/rust-cache@v2

            - name: Set Git identity
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions@github.com"

            - name: Install cargo-release
              run: cargo install cargo-release

            - name: Install git-cliff
              uses: orhun/git-cliff-action@v2
              with:
                  config: cliff.toml
                  args: --verbose

            - name: Build version arguments
              id: version_args
              run: |
                  if [ "${{ inputs.version }}" != "" ]; then
                    # Manual version
                    echo "VERSION_ARG=--version ${{ inputs.version }}" >> $GITHUB_OUTPUT
                  else
                    # Use level
                    echo "VERSION_ARG=--${{ inputs.level }}" >> $GITHUB_OUTPUT
                  fi

                  if [ "${{ inputs.dry-run }}" = "true" ]; then
                    echo "DRY_RUN_ARG=--dry-run" >> $GITHUB_OUTPUT
                  else
                    echo "DRY_RUN_ARG=" >> $GITHUB_OUTPUT
                  fi

            - name: Run cargo release
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
                  WORKSPACE_ROOT: ${{ github.workspace }}
                  GIT_CREDENTIALS: https://x-access-token:${{ github.token }}@github.com
              run: |
                  echo "Running cargo release with args: ${{ steps.version_args.outputs.VERSION_ARG }} ${{ steps.version_args.outputs.DRY_RUN_ARG }}"
                  cargo release ${{ steps.version_args.outputs.VERSION_ARG }} ${{ steps.version_args.outputs.DRY_RUN_ARG }} --execute
